[CmdletBinding()]
param(
  [Parameter(Mandatory = $true)]
  [string]$Source,
  [string]$SiteUrl = "https://xingzhe-lab.github.io/investment-notes"
)

$ErrorActionPreference = "Stop"
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$targetRoot = Join-Path $repoRoot "content\杂文\股票作手回忆录"
$marker = Join-Path $targetRoot ".generated-livermore-cards"
$messagesRoot = Join-Path $repoRoot "static\livermore-cards"
$messagesPath = Join-Path $messagesRoot "messages.json"

if (-not (Test-Path -LiteralPath $Source -PathType Container)) {
  throw "找不到书籍目录：$Source"
}

$chapters = Get-ChildItem -LiteralPath $Source -File -Filter "*.docx" |
  ForEach-Object {
    if ($_.BaseName -match '^\((\d+)\)\s*(.+)$') {
      [pscustomobject]@{ Number = [int]$matches[1]; Title = $matches[2].Trim(); File = $_ }
    }
  } |
  Sort-Object Number

if ($chapters.Count -ne 24) {
  throw "章节数量异常：找到 $($chapters.Count) 个，预期 24 个。"
}

if (Test-Path -LiteralPath $targetRoot) {
  if (-not (Test-Path -LiteralPath $marker)) {
    throw "目标目录不是由本脚本生成，已停止以保护现有内容：$targetRoot"
  }
  Remove-Item -LiteralPath $targetRoot -Recurse -Force
}

New-Item -ItemType Directory -Path $targetRoot -Force | Out-Null
New-Item -ItemType Directory -Path $messagesRoot -Force | Out-Null
Set-Content -LiteralPath $marker -Value "Generated by import-livermore-cards.ps1" -Encoding utf8

$cards = [System.Collections.Generic.List[object]]::new()
foreach ($chapter in $chapters) {
  $number = $chapter.Number
  $cardTitle = "《股票作手回忆录》{0:D2}｜{1}" -f $number, $chapter.Title
  $fileName = "{0:D2}-{1}.md" -f $number, $chapter.Title
  $target = Join-Path $targetRoot $fileName

  $pandocLines = & pandoc --from=docx --to=gfm --wrap=none $chapter.File.FullName
  if ($LASTEXITCODE -ne 0) { throw "Pandoc 转换失败：$($chapter.File.FullName)" }
  $body = ($pandocLines -join "`n").Trim()
  $parts = [regex]::Split($body, '\n\s*\n') | ForEach-Object { $_.Trim() } | Where-Object { $_ }

  if ($parts.Count -gt 0 -and $parts[0] -match '^\\?\(\d+\\?\)') {
    $parts = @($parts | Select-Object -Skip 1)
  }
  if ($parts.Count -gt 0 -and $parts[0] -match '^\d{4}年\d{1,2}月\d{1,2}日$') {
    $parts = @($parts | Select-Object -Skip 1)
  }
  if ($parts.Count -gt 0 -and $parts[0] -match '^\d{1,2}:\d{2}$') {
    $parts = @($parts | Select-Object -Skip 1)
  }
  $parts = @($parts | Where-Object {
      $_ -notmatch '^\d{4}年\d{1,2}月\d{1,2}日$' -and
      $_ -notmatch '^\d{1,2}:\d{2}$' -and
      $_ -notmatch '^(?:---|\* \*)$'
    })

  $body = ($parts -join "`n`n")
  $body = $body -replace '(?s)<img\s+[^>]*?(?:width|height):0\.25in[^>]*?/?>', ''
  $body = $body.Replace([string][char]0x00A0, ' ').Replace([string][char]0x3000, ' ').Replace([string][char]0x200B, '')
  $body = [regex]::Replace($body, '[ \t]+(?=\r?$)', '', 'Multiline')
  $body = [regex]::Replace($body, '(\r?\n){3,}', "`n`n").Trim()

  $previous = if ($number -gt 1) { "[[{0:D2}-{1}|← 上一张]]" -f ($number - 1), $chapters[$number - 2].Title } else { "" }
  $next = if ($number -lt $chapters.Count) { "[[{0:D2}-{1}|下一张 →]]" -f ($number + 1), $chapters[$number].Title } else { "" }
  $navigation = @($previous, "[[index|目录]]", $next) | Where-Object { $_ } 

  $frontMatterTitle = $cardTitle.Replace('"', '\"')
  $document = @(
    "---"
    "title: `"$frontMatterTitle`""
    "description: `"《股票作手回忆录》第 $number 章阅读卡片：$($chapter.Title)`""
    "tags:"
    "  - 投资"
    "  - 利弗莫尔"
    "  - 股票作手回忆录"
    "  - 读书卡片"
    "---"
    ""
    "# $cardTitle"
    ""
    "> 第 $number / $($chapters.Count) 张 · 章节阅读卡片"
    ""
    ($navigation -join " · ")
    ""
    $body
    ""
    "---"
    ""
    ($navigation -join " · ")
    ""
  ) -join "`n"

  Set-Content -LiteralPath $target -Value $document -Encoding utf8

  $slug = "杂文/股票作手回忆录/" + [System.IO.Path]::GetFileNameWithoutExtension($fileName)
  $encodedSlug = ($slug -split '/' | ForEach-Object { [uri]::EscapeDataString($_) }) -join '/'
  $url = "$SiteUrl/$encodedSlug"
  $cards.Add([pscustomobject]@{
      index = $number
      title = $cardTitle
      page_url = $url
      text = "$cardTitle`n`n第 $number / $($chapters.Count) 张章节卡片`n阅读全文：$url"
    })
}

$indexLines = [System.Collections.Generic.List[string]]::new()
$indexLines.Add('---')
$indexLines.Add('title: "《股票作手回忆录》章节卡片"')
$indexLines.Add('description: "《股票作手回忆录》24 章阅读卡片目录"')
$indexLines.Add('tags:')
$indexLines.Add('  - 投资')
$indexLines.Add('  - 利弗莫尔')
$indexLines.Add('  - 股票作手回忆录')
$indexLines.Add('  - 读书卡片')
$indexLines.Add('---')
$indexLines.Add('')
$indexLines.Add('# 《股票作手回忆录》章节卡片')
$indexLines.Add('')
$indexLines.Add('> 全书按原始 24 个章节拆分，每章一张卡片。')
$indexLines.Add('')
foreach ($chapter in $chapters) {
  $indexLines.Add(("- [[{0:D2}-{1}|{0:D2}｜{1}]]" -f $chapter.Number, $chapter.Title))
}
$indexLines.Add('')
Set-Content -LiteralPath (Join-Path $targetRoot 'index.md') -Value ($indexLines -join "`n") -Encoding utf8

$cards | ConvertTo-Json -Depth 4 | Set-Content -LiteralPath $messagesPath -Encoding utf8
Write-Output "已生成 $($cards.Count) 张章节卡片、1 张目录卡和 Telegram 发布清单：$messagesPath"
