[CmdletBinding()]
param(
  [string]$Source = "C:\Obsidian\投资_md",
  [int]$FirstBook = 72,
  [int]$LastBook = 169
)

$ErrorActionPreference = "Stop"
$repoRoot = Join-Path $PSScriptRoot ".."
$collection = Join-Path $repoRoot "content\投资书库"
$manifest = Join-Path $repoRoot "content\.telegram-publish-batch.json"
$collectionMarker = Join-Path $collection ".generated-book-collection"

if (-not (Test-Path -LiteralPath $Source)) {
  throw "找不到投资笔记目录：$Source"
}

if (Test-Path -LiteralPath $collection) {
  if (-not (Test-Path -LiteralPath $collectionMarker)) {
    throw "目标目录不是由本脚本生成，已停止以保护现有内容：$collection"
  }
  Remove-Item -LiteralPath $collection -Recurse -Force
}

New-Item -ItemType Directory -Path $collection -Force | Out-Null
Set-Content -LiteralPath $collectionMarker -Value "Generated by merge-investment-books.ps1" -Encoding utf8

$books = Get-ChildItem -LiteralPath $Source -Directory |
  ForEach-Object {
    if ($_.Name -match '^\((\d+)\)') {
      [pscustomobject]@{ Number = [int]$matches[1]; Directory = $_ }
    }
  } |
  Where-Object { $_.Number -ge $FirstBook -and $_.Number -le $LastBook } |
  Sort-Object Number

if ($books.Count -ne ($LastBook - $FirstBook + 1)) {
  throw "书籍目录数量异常：找到 $($books.Count) 个，预期 $($LastBook - $FirstBook + 1) 个。"
}

$publishedFiles = [System.Collections.Generic.List[string]]::new()
foreach ($book in $books) {
  $chapters = Get-ChildItem -LiteralPath $book.Directory.FullName -Recurse -File -Filter *.md |
    Sort-Object @{ Expression = { if ($_.Name -match '\((\d+)\)') { [int]$matches[1] } else { [int]::MaxValue } } }, FullName
  if ($chapters.Count -eq 0) { throw "书籍没有 Markdown 章节：$($book.Directory.FullName)" }

  $title = $book.Directory.Name
  $fileName = ("{0:D3} {1}.md" -f $book.Number, ($title -replace '^\(\d+\)\s*', ''))
  $sections = [System.Collections.Generic.List[string]]::new()
  $sections.Add("---")
  $sections.Add(("title: `"{0}`"" -f $title.Replace('"', '\"')))
  $sections.Add("---")
  $sections.Add("")
  $sections.Add(("# {0}" -f $title))
  $sections.Add("")
  $sections.Add(("> 合并自 {0} 个 Markdown 章节。" -f $chapters.Count))
  $sections.Add("")

  foreach ($chapter in $chapters) {
    $chapterTitle = [System.IO.Path]::GetFileNameWithoutExtension($chapter.Name)
    $chapterContent = (Get-Content -LiteralPath $chapter.FullName -Raw -Encoding utf8).Trim()
    $sections.Add(("## {0}" -f $chapterTitle))
    $sections.Add("")
    $sections.Add($chapterContent)
    $sections.Add("")
  }

  $target = Join-Path $collection $fileName
  Set-Content -LiteralPath $target -Value ($sections -join [Environment]::NewLine) -Encoding utf8
  $publishedFiles.Add(("content/投资书库/{0}" -f $fileName))
}

@{ collection = "投资书库"; files = $publishedFiles; generatedAt = (Get-Date).ToString("o") } |
  ConvertTo-Json -Depth 3 |
  Set-Content -LiteralPath $manifest -Encoding utf8

Write-Output ("已合并 {0} 本书，生成 {1}" -f $books.Count, $collection)
