[CmdletBinding()]
param(
  [string]$Source = "C:\Obsidian\投资_md\telegram",
  [ValidateSet("Normal", "Batch")]
  [string]$Mode = "Normal",
  [switch]$Publish,
  [switch]$Prune
)

$ErrorActionPreference = "Stop"
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$contentRoot = (Resolve-Path (Join-Path $repoRoot "content")).Path
$targetRoot = Join-Path $contentRoot "杂文\telegram"
$marker = Join-Path $targetRoot ".generated-telegram-sync"
$manifest = Join-Path $repoRoot "static\telegram-notes\messages.json"
$siteUrl = "https://xingzhe-lab.github.io/investment-notes"
$excludedDirectories = @(".obsidian", ".git", ".trash", "private", "_private")
$allowedExtensions = @(".md", ".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg", ".avif", ".pdf")

if (-not (Test-Path -LiteralPath $Source -PathType Container)) {
  throw "找不到源目录：$Source"
}

$sourceRoot = (Resolve-Path -LiteralPath $Source).Path
$targetFull = [System.IO.Path]::GetFullPath($targetRoot)
$allowedTargetPrefix = [System.IO.Path]::GetFullPath((Join-Path $contentRoot "杂文")) + [System.IO.Path]::DirectorySeparatorChar
if (-not $targetFull.StartsWith($allowedTargetPrefix, [System.StringComparison]::OrdinalIgnoreCase)) {
  throw "目标目录越界，已停止：$targetFull"
}
if ((Test-Path -LiteralPath $targetFull) -and -not (Test-Path -LiteralPath $marker)) {
  throw "目标目录不是由本脚本生成，已停止以保护现有内容：$targetFull"
}

$dirtyPaths = @(
  git -C $repoRoot diff --name-only
  git -C $repoRoot ls-files --others --exclude-standard
) | Where-Object { $_ }
$unrelatedDirty = $dirtyPaths | Where-Object {
  $_ -ne "static/telegram-notes/messages.json" -and
  -not $_.StartsWith("content/杂文/telegram/", [System.StringComparison]::OrdinalIgnoreCase)
}
if ($Publish -and $unrelatedDirty) {
  throw "Git 仓库存在与本流程无关的未提交改动。请先处理：$($unrelatedDirty -join ', ')"
}

New-Item -ItemType Directory -Path $targetFull -Force | Out-Null
Set-Content -LiteralPath $marker -Value "Generated by sync-telegram-notes.ps1" -Encoding utf8
New-Item -ItemType Directory -Path (Split-Path -Parent $manifest) -Force | Out-Null

$sourceFiles = Get-ChildItem -LiteralPath $sourceRoot -Recurse -Force -File |
  Where-Object {
    $relativeParts = $_.FullName.Substring($sourceRoot.Length).TrimStart('\', '/') -split '[\/]'
    -not ($relativeParts | Where-Object { $_ -in $excludedDirectories }) -and
    $_.Extension.ToLowerInvariant() -in $allowedExtensions
  }

$publishable = [System.Collections.Generic.List[object]]::new()
$sourceRelativeSet = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
foreach ($file in $sourceFiles) {
  $relative = $file.FullName.Substring($sourceRoot.Length).TrimStart('\', '/')
  $destination = Join-Path $targetFull $relative
  $destinationParent = Split-Path -Parent $destination
  New-Item -ItemType Directory -Path $destinationParent -Force | Out-Null

  $isMarkdown = $file.Extension.Equals('.md', [System.StringComparison]::OrdinalIgnoreCase)
  $isPrivate = $false
  if ($isMarkdown) {
    $head = (Get-Content -LiteralPath $file.FullName -TotalCount 40 -Encoding utf8) -join "`n"
    $isPrivate = $head -match '(?im)^\s*(?:private\s*:\s*true|publish\s*:\s*false)\s*$'
  }
  if ($isPrivate) { continue }
  $sourceRelativeSet.Add($relative) | Out-Null

  $changed = -not (Test-Path -LiteralPath $destination)
  if (-not $changed) {
    $changed = (Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash -ne
      (Get-FileHash -LiteralPath $destination -Algorithm SHA256).Hash
  }
  Copy-Item -LiteralPath $file.FullName -Destination $destination -Force
  if ($isMarkdown -and $changed) {
    $publishable.Add([pscustomobject]@{ Source = $file; Relative = $relative; Destination = $destination })
  }
}

if ($Prune) {
  Get-ChildItem -LiteralPath $targetFull -Recurse -Force -File |
    Where-Object { $_.FullName -ne $marker } |
    ForEach-Object {
      $relative = $_.FullName.Substring($targetFull.Length).TrimStart('\', '/')
      if (-not $sourceRelativeSet.Contains($relative)) {
        Remove-Item -LiteralPath $_.FullName -Force
      }
    }
}

if ($Mode -eq "Normal" -and $publishable.Count -gt 5) {
  throw "本次有 $($publishable.Count) 篇新增或修改，超过普通发布上限 5 篇。请检查范围，确认后改用 -Mode Batch。"
}

function Get-Title([string]$Text, [string]$Fallback) {
  $frontMatter = [regex]::Match($Text, '(?ms)^---\s*\n.*?^title:\s*["'']?(.+?)["'']?\s*$.*?^---\s*$')
  if ($frontMatter.Success) { return $frontMatter.Groups[1].Value.Trim(' ', '"', "'") }
  $heading = [regex]::Match($Text, '(?m)^#\s+(.+?)\s*$')
  if ($heading.Success) { return $heading.Groups[1].Value.Trim() }
  return $Fallback
}

function Get-Summary([string]$Text) {
  $withoutFrontMatter = [regex]::Replace($Text, '(?ms)^---\s*\n.*?^---\s*$', '')
  $paragraph = ([regex]::Split($withoutFrontMatter, '\r?\n\s*\r?\n') |
      ForEach-Object { $_.Trim() } |
      Where-Object { $_ -and $_ -notmatch '^(?:#|>|!\[|\||```)' } |
      Select-Object -First 1)
  if (-not $paragraph) { return "新文章已发布。" }
  $paragraph = $paragraph -replace '!\[[^\]]*\]\([^)]+\)', ''
  $paragraph = $paragraph -replace '\[([^\]]+)\]\([^)]+\)', '$1'
  $paragraph = $paragraph -replace '[*_`]', ''
  $paragraph = [regex]::Replace($paragraph, '\s+', ' ').Trim()
  if ($paragraph.Length -gt 180) { return $paragraph.Substring(0, 180) + "…" }
  return $paragraph
}

function Get-QuartzSlug([string]$Relative) {
  $segments = ($Relative -replace '\.md$', '') -split '[\/]'
  if ($segments[-1] -eq 'index') {
    if ($segments.Count -eq 1) { $segments = @() } else { $segments = $segments[0..($segments.Count - 2)] }
  }
  $segments = @('杂文', 'telegram') + $segments
  $clean = $segments | ForEach-Object {
    $segment = $_ -replace '\s', '-' -replace '&', '-and-' -replace '%', '-percent' -replace '[?#<>:"|*]', ''
    [uri]::EscapeDataString($segment.ToLowerInvariant())
  }
  return $clean -join '/'
}

$messages = foreach ($item in $publishable) {
  $text = Get-Content -LiteralPath $item.Destination -Raw -Encoding utf8
  $title = Get-Title $text ([System.IO.Path]::GetFileNameWithoutExtension($item.Relative))
  $summary = Get-Summary $text
  $url = "$siteUrl/$(Get-QuartzSlug $item.Relative)"
  [pscustomobject]@{
    index = $publishable.IndexOf($item) + 1
    title = $title
    page_url = $url
    text = "$title`n`n$summary`n`n阅读全文：$url"
  }
}
ConvertTo-Json -InputObject @($messages) -Depth 4 | Set-Content -LiteralPath $manifest -Encoding utf8

Write-Output "源目录：$sourceRoot"
Write-Output "已同步文件：$($sourceFiles.Count)；待通知文章：$($publishable.Count)；模式：$Mode"
if (-not $Publish) {
  Write-Output "预览同步完成。确认后加 -Publish 才会构建、提交、推送并通知频道。"
  exit 0
}
if ($publishable.Count -eq 0) {
  Write-Output "没有新增或修改的 Markdown，跳过发布。"
  exit 0
}

& npx quartz build
if ($LASTEXITCODE -ne 0) { throw "Quartz 本地构建失败，未提交。" }

git -C $repoRoot add -- "content/杂文/telegram" "static/telegram-notes/messages.json"
git -C $repoRoot commit -m "[publish-telegram-notes] Publish $($publishable.Count) notes to Zawen"
if ($LASTEXITCODE -ne 0) { throw "Git 提交失败。" }
git -C $repoRoot push origin main
if ($LASTEXITCODE -ne 0) { throw "Git 推送失败。" }
Write-Output "已推送。GitHub Pages 部署成功后，工作流将向‘杂文’频道顺序发送 $($publishable.Count) 条消息。"
